name: Module checks
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer:v1
      - uses: actions/checkout@v2
      - name: validate composer json
        run: composer validate
      - name: PHPUnit
        run: |
          echo '{"http-basic": {"repo.magento.com": {"username": "${{ secrets.REPO_USERNAME }}","password": "${{ secrets.REPO_PASS }}"}}}' > auth.json
          composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.6 m23
          mkdir -p m23/app/code/Buckaroo/Magento2/
          rsync -r --exclude='m23' ./ m23/app/code/Buckaroo/Magento2/
          cd m23
          vendor/phpunit/phpunit/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Buckaroo/Magento2
      - name: get phpcs
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - name: magento coding standard
        run: |
          composer create-project magento/magento-coding-standard --stability=stable magento-coding-standard
          ./magento-coding-standard/vendor/bin/phpcs --standard=Magento2 . --ignore=magento-coding-standard/*