name: Module checks
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer:v1
      - uses: actions/checkout@v2
      - name: validate composer json
        run: composer validate
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/${{ env.namespace }}-source/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: PHPUnit
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          url="https://api.github.com/repos/buckaroo-it/Magento2/pulls/$pull_number/files"
          echo $url
          curl $url > files_changed
          cat files_changed | grep '"filename"' | sed 's/\"filename\"\: \"//' | sed 's/\",//' | xargs ls                    
