name: Module checks
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: b0daf22bbe19
    steps:
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer:v1
      - uses: actions/checkout@v2
      - name: validate composer json
        run: composer validate
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}
      - name: PHPUnit
        run: |
          echo '{"http-basic": {"repo.magento.com": {"username": "${{ secrets.REPO_USERNAME }}","password": "${{ secrets.REPO_PASS }}"}}}' > auth.json
          composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.6 m23
          mkdir -p m23/app/code/Buckaroo/Magento2/
          rsync -r --exclude='m23' ./ m23/app/code/Buckaroo/Magento2/
          cd m23
          vendor/phpunit/phpunit/phpunit --filter="Block" -c dev/tests/unit/phpunit.xml.dist app/code/Buckaroo/Magento2
      - name: magento coding standard
        run: |
          cd m23
          ./vendor/bin/phpcs --standard=Magento2  app/code/Buckaroo/Magento2/